# Generated by Django 4.1.3 on 2022-12-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='doras.png', upload_to='profile_pics'),
        ),
    ]
