# Generated by Django 4.1.3 on 2022-12-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='subscription_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
