# Generated by Django 4.1.3 on 2022-12-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_image'),
        ('account', '0002_profile'),
    ]

    operations = [
    ]
