# Generated by Django 4.1.3 on 2022-12-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_subscription_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='subscription_expired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
