# Generated by Django 4.1.3 on 2022-11-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
        ('account', '0004_alter_customer_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Account',
        ),
    ]
