# Generated by Django 4.1.3 on 2022-11-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('A', 'Available'), ('UA', 'Unavailable')], default='A', max_length=2),
        ),
    ]
