# Generated by Django 4.1.3 on 2022-11-24 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_course_course_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
