# Generated by Django 4.1.3 on 2022-11-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_course_category_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
