# Generated by Django 4.1.3 on 2022-12-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='Doras Sibachao', max_length=50),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
