# Generated by Django 4.1.3 on 2022-12-22 10:13

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[500, 300], upload_to='course/course_image/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(null=True, upload_to='course/course_video'),
        ),
    ]
