# Generated by Django 4.1.3 on 2022-12-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='subscription_type',
            field=models.CharField(choices=[('M', 'Monthly'), ('A', 'Annually')], default='M', max_length=1),
        ),
    ]
